trigger:
- master

pool:
  name: 'mylocalpool'
  demands: agent.name -equals pop-os  

steps:
- checkout: self  

- script: |
    docker build -t aspnet-app-image:$(Build.BuildId) .
  displayName: 'Docker Build '

- script: |
    
    kubectl config use-context docker-desktop

    sed -i 's|aspnet-app-image:latestaspnet-app-image:$(Build.BuildId)|g' deployment.yaml
    
    kubectl apply -f deployment.yaml
    
    kubectl apply -f service.yaml || true
  displayName: 'Kubernetes Deploy '